// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {time} from '../models';
import {models} from '../models';
import {context} from '../models';

export function AddStockEntry(arg1:string,arg2:number,arg3:number,arg4:time.Time,arg5:any):Promise<models.StockEntry>;

export function CreateProduct(arg1:string,arg2:string,arg3:string,arg4:any):Promise<models.Product>;

export function CreateStockOutput(arg1:string,arg2:number,arg3:time.Time,arg4:any,arg5:any):Promise<models.StockOutput>;

export function DeleteProduct(arg1:string):Promise<void>;

export function GetAllTransactions():Promise<Array<models.Transaction>>;

export function GetProductByID(arg1:string):Promise<models.Product>;

export function GetProducts():Promise<Array<models.Product>>;

export function GetStockEntriesForProduct(arg1:string):Promise<Array<models.StockEntry>>;

export function GetStockOutputLines(arg1:string):Promise<Array<models.StockOutputLine>>;

export function GetStockOutputsForProduct(arg1:string):Promise<Array<models.StockOutput>>;

export function GetTransactionsForProduct(arg1:string):Promise<Array<models.Transaction>>;

export function SetContext(arg1:context.Context):Promise<void>;

export function UpdateProduct(arg1:string,arg2:string,arg3:string,arg4:string,arg5:any):Promise<models.Product>;

export function UpdateStockEntry(arg1:string,arg2:number,arg3:time.Time,arg4:any,arg5:any):Promise<models.StockEntry>;
