// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddStockEntry(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['services']['InventoryService']['AddStockEntry'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateProduct(arg1, arg2, arg3, arg4) {
  return window['go']['services']['InventoryService']['CreateProduct'](arg1, arg2, arg3, arg4);
}

export function CreateStockOutput(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['services']['InventoryService']['CreateStockOutput'](arg1, arg2, arg3, arg4, arg5);
}

export function DeleteProduct(arg1) {
  return window['go']['services']['InventoryService']['DeleteProduct'](arg1);
}

export function GetAllTransactions() {
  return window['go']['services']['InventoryService']['GetAllTransactions']();
}

export function GetProductByID(arg1) {
  return window['go']['services']['InventoryService']['GetProductByID'](arg1);
}

export function GetProducts() {
  return window['go']['services']['InventoryService']['GetProducts']();
}

export function GetStockEntriesForProduct(arg1) {
  return window['go']['services']['InventoryService']['GetStockEntriesForProduct'](arg1);
}

export function GetStockOutputLines(arg1) {
  return window['go']['services']['InventoryService']['GetStockOutputLines'](arg1);
}

export function GetStockOutputsForProduct(arg1) {
  return window['go']['services']['InventoryService']['GetStockOutputsForProduct'](arg1);
}

export function GetTransactionsForProduct(arg1) {
  return window['go']['services']['InventoryService']['GetTransactionsForProduct'](arg1);
}

export function SetContext(arg1) {
  return window['go']['services']['InventoryService']['SetContext'](arg1);
}

export function UpdateProduct(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['services']['InventoryService']['UpdateProduct'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateStockEntry(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['services']['InventoryService']['UpdateStockEntry'](arg1, arg2, arg3, arg4, arg5);
}
